Olwa/dev
Sean-Nishi/Reluctant-Hero pull request #145
Opened 2023-10-28 15:43 UTC by owalk

2023-11-04 16:41 UTC, owalk commented
@Sean-Nishi  this is now ready for review.

2023-11-06 18:54 UTC, Sean-Nishi requested changes

2023-11-06 18:54 UTC, Sean-Nishi commented on game/entities/entity.py
> +        and the tracker will be reduced by that 1 pixel.
```suggestion
        and the tracker will be modified by that 1 pixel towards 0.
```

2023-11-06 19:35 UTC, Sean-Nishi approved these changes

2023-11-06 19:37 UTC, merged