Olwa/117
Sean-Nishi/Reluctant-Hero pull request #158
Opened 2023-11-04 20:59 UTC by owalk

Entities now load from the maps created by Tiled map editor.

2023-11-04 21:08 UTC, owalk commented
The surface key color logic is broken :(

I've made a new [issue](https://github.com/Sean-Nishi/Reluctant-Hero/issues/159) to fix this later.

2023-11-06 18:36 UTC, Sean-Nishi commented on game/levels/level.py
> +        # add stuff to their sprite groups
Remove 60-62, out of commit scope.

2023-11-06 18:46 UTC, Sean-Nishi requested changes
Looks good except for out of scope comments.

2023-11-06 18:46 UTC, Sean-Nishi commented on game/levels/level.py
> +        sprite_group = pygame.sprite.Group()
remove this line4

2023-11-06 18:46 UTC, Sean-Nishi commented on game/levels/level.py
> +        x = 0
doc that this is the default pos

2023-11-06 19:43 UTC, Sean-Nishi approved these changes

2023-11-06 19:43 UTC, merged