player interactions
Sean-Nishi/Reluctant-Hero pull request #251
Opened 2023-12-10 18:21 UTC by owalk

Also fixed the color key bug

2023-12-10 18:45 UTC, Sean-Nishi commented on game/levels/level.py
> +                    sprite.image.set_colorkey(black, pygame.RLEACCEL)
We can use pygame.Color.black instead of creating a var black.
https://www.pygame.org/docs/ref/color.html
https://www.pygame.org/docs/ref/color_list.html

2023-12-10 18:47 UTC, Sean-Nishi commented on game/filemanagement/spriteSheet.py
> +    COLOR_KEY_BLACK = (255, 255, 255)
We can assign the global consts as pygame.color.black (not sure if correct syntax)
https://www.pygame.org/docs/ref/color.html

2023-12-10 18:48 UTC, Sean-Nishi commented on game/enums/eatenPowers.py
> +        the value representing an empty stomach
Attribute descriptions start with a Capitalized letter. basic_skeleton and damsel both say they are representing value of empty stomach.

2023-12-10 19:03 UTC, Sean-Nishi commented on game/tiles/entities/NPCs/skeleton.py
> +        if self.current_state != self.states.Thrown:
I think this is where the skeleton can be thrown through walls bug is. If they are thrown/states.Thrown then there is no collision_handler().
Let me know if you already solved this bug.

2023-12-10 19:06 UTC, Sean-Nishi requested changes
See comments.

2023-12-10 19:12 UTC, owalk commented on game/levels/level.py
> +                    sprite.image.set_colorkey(black, pygame.RLEACCEL)
fixed all these, this is much better!

2023-12-10 19:12 UTC, owalk commented on game/filemanagement/spriteSheet.py
> +    COLOR_KEY_BLACK = (255, 255, 255)
or even better, just straight up use the pygame constants

2023-12-11 03:47 UTC, Sean-Nishi commented on game/enums/eatenPowers.py
> +        The value representing a basic skeleton was eaten
Grammar/complete sentences.
```suggestion
        The value representing a basic skeleton that was eaten
    damsel : Enum
        The value representing a damsel that was eaten
```

2023-12-11 03:47 UTC, Sean-Nishi commented on game/filemanagement/spriteSheet.py
> +    def __init__(self, filename: str = None, colorKey=None):
Consistency with spacing after assignment.

2023-12-11 03:54 UTC, Sean-Nishi requested changes
Should just be 2 comments this time.

2023-12-11 18:01 UTC, owalk commented on game/levels/level.py
> +                    sprite.image.set_colorkey(black, pygame.RLEACCEL)
After checking this again, for whatever reason using a pygame color object instead of the Tuple breaks the logic here, I'm not sure why

2023-12-12 18:38 UTC, owalk commented on game/filemanagement/spriteSheet.py
> +    def __init__(self, filename: str = None, colorKey=None):
fixed

2023-12-12 19:03 UTC, Sean-Nishi approved these changes

2023-12-12 19:04 UTC, merged