211 implement main menu
Sean-Nishi/Reluctant-Hero pull request #275
Opened 2023-12-12 20:48 UTC by Sean-Nishi

2023-12-12 21:29 UTC, owalk requested changes

2023-12-12 21:29 UTC, owalk commented on game/game.py
> +        # if we quit, exit game
remove this comment so its not added and removed in same PR

2023-12-12 21:29 UTC, owalk commented on game/levels/level.py
> +    def add_obstacles(self):
add return type hint

2023-12-12 21:29 UTC, owalk commented on game/levels/levelManager.py
> +        self.clock = pygame.time.Clock()
Either todo for added setter/getter to clock, or switch to setter/getter

2023-12-12 21:29 UTC, owalk commented on game/levels/mainMenu.py
> +
rm newline

2023-12-12 21:29 UTC, owalk commented on game/levels/mainMenu.py
> +        # create a pygame_menu inside our display surface
update comment

2023-12-12 21:29 UTC, owalk commented on game/levels/mainMenu.py
> +        """Set user selection for LevelManager.
```Suggestion
        """Set user selection for MainMenu.

        Intended for use in LevelManager.
        """
```

2023-12-12 21:29 UTC, owalk commented on game/levels/mainMenu.py
> +    def set_user_selection(self, selection: str):
add return type hint

2023-12-12 21:29 UTC, owalk commented on game/cameraControl/cameraManager.py
> +    _halfHeight: int
snake case

2023-12-12 21:29 UTC, owalk commented on game/cameraControl/cameraManager.py
> +    _halfWidth: int
snake case

2023-12-12 21:29 UTC, owalk commented on game/cameraControl/cameraManager.py
> +    _displaySurface: pygame.Surface
snake case

2023-12-12 21:29 UTC, owalk commented on game/cameraControl/cameraManager.py
> +    _offset: vector2
snake case

2023-12-12 21:29 UTC, owalk commented on game/cameraControl/cameraManager.py
> +    _playerCharacter: Player
snake case

2023-12-12 21:29 UTC, owalk commented on game/cameraControl/cameraManager.py
> +            The player character entities move around
```Suggestion
            The player character that entities move around
```

2023-12-12 21:29 UTC, owalk commented on game/game.py
> -        # if we quit, exit game
should not rlly get added in prev commit in the same PR

2023-12-12 21:29 UTC, owalk commented on game/levels/level.py
> +        LevelManager's music mixer which to load level specific music to
```Suggestion
        LevelManager's music mixer for level specific music
```

2023-12-12 21:29 UTC, owalk commented on game/levels/mainMenu.py
> +        Changes user selection to "Level" and disables the menu
```Suggestion
        Changes user selection to Level instance and disables the menu
```

2023-12-13 16:22 UTC, Sean-Nishi commented on game/cameraControl/cameraManager.py
> +            The player character entities move around
Also changed init parameter and docstring to snake_case to be consistent

2023-12-13 16:40 UTC, owalk commented on game/cameraControl/cameraManager.py
> +            The player character entities move around
This comment was missed

2023-12-13 16:41 UTC, owalk commented on game/levels/level.py
> +        LevelManager's music mixer which to load level specific music to
this comment was missed

2023-12-13 16:42 UTC, owalk commented on game/levels/mainMenu.py
> +        Changes user selection to "Level" and disables the menu
This comment was missed

2023-12-13 16:44 UTC, owalk commented
@Sean-Nishi Can you assign yourself to the PR and include any issues this will close

2023-12-13 18:34 UTC, owalk approved these changes

2023-12-13 18:34 UTC, merged