213 update skeleton docs
Sean-Nishi/Reluctant-Hero pull request #281
Opened 2023-12-13 20:44 UTC by Sean-Nishi

2023-12-15 19:27 UTC, owalk requested changes
It looks like the code does not compile on this branch, can you get it to compile again?

2023-12-15 19:27 UTC, owalk commented on game/tiles/entities/characters/NPCs/skeleton.py
> +    as described in the docs. Still uses NPC's collision_handler method.
```Suggestion
    Inherits from NPC. Defines the skeleton-specific logic.
```

2023-12-15 19:27 UTC, owalk commented on game/tiles/entities/characters/player.py
> +            The sprite groups the player is part of, used in Character constructor
It's from the sprite constructor, best to just not even mention it
```Suggestion
            The sprite groups the player is part of
```

2023-12-15 19:27 UTC, owalk commented on game/tiles/entities/characters/player.py
> +    def _eaten_power(self) -> EatenPowers:
properties should be public access

the property will set the private access _eaten_power but it is called eaten_power denoting public access

```Suggestion
    def eaten_power(self) -> EatenPowers:
```

2023-12-15 19:27 UTC, owalk commented on game/tiles/entities/characters/player.py
> +        _eaten_power: EatenPowers
privately stored attr should not be mentioned in the public getter. Just refer to it by the method name
```Suggestion
        eaten_power: EatenPowers
```

2023-12-15 19:27 UTC, owalk commented on game/tiles/entities/characters/player.py
> +    def _eaten_power(self, new_value) -> None:
```Suggestion
    @eaten_power.setter
    def eaten_power(self, new_value) -> None:
```

2023-12-15 19:27 UTC, owalk commented on game/tiles/entities/characters/player.py
> +        """Input method to handle keyboard input to the player class.
```Suggestion
        """Method to handle keyboard input to the player class.
```

2023-12-15 19:27 UTC, owalk commented on game/tiles/entities/characters/NPCs/damsel.py
> +        collisions: list[int] = self._rect.collidelistall(enemy_sprites)
Does this work? I think pygame looks for a sprite's self.rect to know the sprite's position. Do things still appear in the correct spot when rendered?

2023-12-15 19:41 UTC, owalk commented on game/tiles/entities/characters/player.py
> +    def _eaten_power(self) -> EatenPowers:
https://www.geeksforgeeks.org/getter-and-setter-in-python/

2023-12-19 21:05 UTC, owalk requested changes

2023-12-19 21:05 UTC, owalk commented on game/filemanagement/spriteSheet.py
> +            The pygame.Surface containing the image, rect, and background color
```Suggestion
            The pygame.Surface containing the image of the specified rect from the given animations
```

2023-12-19 21:05 UTC, owalk commented on game/filemanagement/spriteSheet.py
> +            The list of images to go through
```Suggestion
            The list of rects containing images to go through
```

2023-12-19 21:47 UTC, Sean-Nishi commented on game/tiles/entities/characters/NPCs/NPC.py
> +    def collided_with_player(self) -> None:
Method was moved up to reflect where it is in the Method docstrings

2023-12-20 18:54 UTC, owalk requested changes

2023-12-20 18:54 UTC, owalk commented on game/tiles/entities/characters/NPCs/NPC.py
> +            The boolean value of of entity is facing towards this entity
```Suggestion
            The boolean value of entity is facing towards this entity
```

2023-12-20 18:54 UTC, owalk commented on game/tiles/entities/characters/character.py
> +            The coordinates to get the distance from
```Suggestion
            The coordinates to get the distance from the coords
```

2023-12-20 18:54 UTC, owalk commented on game/tiles/entities/characters/character.py
> +            The distance the coodinates are from this character
```Suggestion
            The distance the coordinates are from this character
```

2023-12-20 18:54 UTC, owalk commented on game/tiles/entities/characters/NPCs/NPC.py
> +    ) -> bool
the other methods here use a colon instead of an arrow

2023-12-20 18:54 UTC, owalk commented on game/tiles/entities/characters/character.py
> +            The axis we want to inspect
remove use of the word "we"

2023-12-20 18:54 UTC, owalk commented on game/tiles/tile.py
> +        self._hitbox: pygame.Rect
maybe just initialize these, for the rect, do a temp rect

2023-12-20 18:54 UTC, owalk commented on game/filemanagement/spriteSheet.py
> +            print("Fatal ERROR!! No sprite sheet was set!")
can be ignored, but this should be in the previous commit where it is introduced

2023-12-20 19:05 UTC, Sean-Nishi commented on game/tiles/entities/characters/NPCs/NPC.py
> +    ) -> bool
Method returns boolean value. No other methods in the NPC.py docstrings use colons to denote return value. Ex. is on line 83

2023-12-20 19:08 UTC, owalk commented on game/tiles/entities/characters/NPCs/NPC.py
> +    ) -> bool
idk why I thought this was an Attribute, looks good

2023-12-20 19:26 UTC, owalk approved these changes

2023-12-20 19:27 UTC, merged