Item work + maintenance
Sean-Nishi/Reluctant-Hero pull request #288
Opened 2023-12-15 19:59 UTC by owalk

2023-12-16 00:23 UTC, Sean-Nishi commented on game/levels/level.py
> +        layout: array of values each representing an individual entity
No params

2023-12-16 00:24 UTC, Sean-Nishi commented on game/tiles/entities/characters/NPCs/NPC.py
> +        spriteSheetPath: str,
new var should be snake_case

2023-12-16 00:25 UTC, Sean-Nishi commented on game/tiles/entities/characters/character.py
> +        spriteSheetPath: str,
new vars should be snake_case

2023-12-16 00:29 UTC, Sean-Nishi commented on game/tiles/entities/entity.py
> +        Animation loop for character
Add other method docstrings like import_assets method

2023-12-16 00:29 UTC, Sean-Nishi commented on game/tiles/entities/entity.py
> +        imageRect: pygame.rect,
new vars should be snake_case

2023-12-16 00:30 UTC, Sean-Nishi commented on game/tiles/entities/items/crystal.py
> +
Remove extra newline

2023-12-16 00:30 UTC, Sean-Nishi commented on game/tiles/entities/items/crystal.py
> +        Parameters
update parameters docstrings

2023-12-16 00:32 UTC, Sean-Nishi commented on game/tiles/entities/items/item.py
> +    sorite_sheet: SpriteSheet
spelling. Also newly added private vars should have "_" in front

2023-12-16 00:33 UTC, Sean-Nishi requested changes
Mostly changing to snake_case for new vars

2023-12-16 14:07 UTC, owalk commented on game/tiles/entities/items/item.py
> +    sorite_sheet: SpriteSheet
So, this one is weird. Python doesn't have private public or protected, so the denotation here would be purely for the dev, but in this case this would be considered a "protected" variable in a language like Java. We don't have a great way to differentiate private vs protected because it's all public.... soo I would prefer to leave things that should be protected without the underscore

2023-12-16 14:11 UTC, owalk commented on game/tiles/entities/items/item.py
> +    sorite_sheet: SpriteSheet
This will come up in your PR a lot since many of the vars you changed to have an underscore would also technically be protected and used in subclasses but are not a part of the API. Let's settle on a way to handle each of the 3 situations for our variable should be private, public, or protected. All public should have setters getters, and all private should be mangled or have underscores, but what do we do for protected?

2023-12-16 14:16 UTC, owalk commented on game/tiles/entities/items/item.py
> +    sorite_sheet: SpriteSheet
okay, sorry for the long comment. it looks like private should be mangled (two underscores), protected should be 1 underscore prefix,  and public should be setters and getters. this tutorial has it like that anyways and it makes sense to me [Tutorial](https://www.tutorialsteacher.com/python/public-private-protected-modifiers#:~:text=Python's%20convention%20to%20make%20an,from%20within%20a%20sub%2Dclass.)

2023-12-16 14:39 UTC, owalk commented on game/levels/level.py
> +        layout: array of values each representing an individual entity
added missing doc strings in class docs

2023-12-16 14:52 UTC, owalk commented on game/tiles/entities/items/item.py
> +    sorite_sheet: SpriteSheet
This is fixed, It required another commit since a lot of changes were out of the scope of the current work.

2023-12-18 17:27 UTC, Sean-Nishi commented on game/tiles/entities/characters/NPCs/NPC.py
> +        pos,
type hint for pos

2023-12-18 17:28 UTC, Sean-Nishi commented on game/tiles/entities/entity.py
> +        import sprite animations
Caps

2023-12-18 17:30 UTC, Sean-Nishi commented on game/tiles/entities/items/item.py
> +    status: str
private attributes should have underscore in front

2023-12-18 17:30 UTC, Sean-Nishi commented on game/tiles/entities/items/item.py
> +        self.status = "idle"
private attributes should have underscore in front

2023-12-18 17:31 UTC, Sean-Nishi requested changes
Only a few more docstring things

2023-12-18 17:42 UTC, owalk commented on game/tiles/entities/items/item.py
> +        self.status = "idle"
I want to make this one public with a getter and setter which is outside the scope of this PR. I can add a TODO above the attr

2023-12-22 18:19 UTC, Sean-Nishi commented on game/levels/level.py
> +    def create_items_from_layout(self) -> None:
typehints for local vars to be consistent

2023-12-22 18:20 UTC, Sean-Nishi commented on game/tiles/entities/characters/NPCs/NPC.py
> +        image_rect: pygame.rect,
type is pygame.Rect
see self._radar near line 122

2023-12-22 18:21 UTC, Sean-Nishi commented on game/tiles/entities/characters/NPCs/damsel.py
> +        damselMovementImagePath = settings.CHARACTER_IMAGES + "NPCs/damsel/damsel.png"
No CamelCase and add type hints

2023-12-22 18:22 UTC, Sean-Nishi commented on game/tiles/entities/characters/NPCs/skeleton.py
> +        skeletonSelfImageRect = pygame.Rect(
No CamelCase and add type hints

2023-12-22 18:25 UTC, Sean-Nishi commented on game/tiles/entities/characters/NPCs/skeleton.py
> +        self.hitbox = self.rect.inflate(-4, 0)
private vars need underscore. I will get to property decorators/safely accessing vars in next pr

2023-12-22 18:26 UTC, Sean-Nishi commented on game/tiles/entities/characters/character.py
> +from dictStructures.animationDict import AnimationDict
Rename file structure to convention.
https://google.github.io/styleguide/pyguide.html#316-naming

2023-12-22 18:26 UTC, Sean-Nishi commented on game/tiles/entities/characters/character.py
> +        image_rect: pygame.rect,
type is pygame.Rect

2023-12-22 18:27 UTC, Sean-Nishi commented on game/tiles/entities/characters/character.py
> +        self.scoreController = ScoreController()
No CamelCase

2023-12-22 18:27 UTC, Sean-Nishi commented on game/tiles/entities/characters/character.py
> +            "imageRect": (
No CamelCase

2023-12-22 18:27 UTC, Sean-Nishi commented on game/tiles/entities/characters/character.py
> +            "imageCount": 3,
No CamelCase

2023-12-22 18:28 UTC, Sean-Nishi commented on game/tiles/entities/characters/character.py
> +            "imageRect": (
No CamelCase

2023-12-22 18:28 UTC, Sean-Nishi commented on game/tiles/entities/characters/character.py
> +            "imageCount": 3,
No CamelCase

2023-12-22 18:28 UTC, Sean-Nishi commented on game/tiles/entities/characters/character.py
> +            "imageRect": (
No CamelCase

2023-12-22 18:28 UTC, Sean-Nishi commented on game/tiles/entities/characters/character.py
> +            "imageCount": 3,
No CamelCase

2023-12-22 18:28 UTC, Sean-Nishi commented on game/tiles/entities/characters/player.py
> +        playerSelfImageRect = pygame.Rect(
No CamelCase

2023-12-22 18:29 UTC, Sean-Nishi commented on game/tiles/entities/entity.py
> +from dictStructures.animationDict import AnimationDict
No CamelCase

2023-12-22 18:29 UTC, Sean-Nishi commented on game/tiles/entities/characters/player.py
> +        super().__init__(groups, pos, playerMovementsPath, playerSelfImageRect)
No CamelCase

2023-12-22 18:29 UTC, Sean-Nishi commented on game/tiles/entities/entity.py
> +    import_assets(self, animationDict: list[AnimationDict])
No CamelCase

2023-12-22 18:30 UTC, Sean-Nishi commented on game/tiles/entities/entity.py
> +        image_rect: pygame.rect,
Type is pygame.Rect

2023-12-22 18:30 UTC, Sean-Nishi commented on game/tiles/entities/entity.py
> +        self.hitbox = self.rect.copy()
No type hints

2023-12-22 18:30 UTC, Sean-Nishi commented on game/tiles/entities/entity.py
> +        animationStrip = self._animations[self._status]
No CamelCase

2023-12-22 18:31 UTC, Sean-Nishi commented on game/tiles/entities/entity.py
> +    def import_assets(self, animationDict: list[AnimationDict]):
No CamelCase

2023-12-22 18:31 UTC, Sean-Nishi commented on game/tiles/entities/entity.py
> +                animation["imageRect"], animation["imageCount"]
No CamelCase

2023-12-22 18:32 UTC, Sean-Nishi commented on game/tiles/entities/items/crystal.py
> +        handle collisions with the item and entities
Capitalize start of sentence

2023-12-22 18:32 UTC, Sean-Nishi commented on game/tiles/entities/items/crystal.py
> +    def __init__(self, groups: pygame.sprite.Group, pos: tuple):
Rename parameter to singular "group"

2023-12-22 18:33 UTC, Sean-Nishi commented on game/tiles/entities/items/crystal.py
> +            The groups this sprite is a part of
Groups should be singular

2023-12-22 18:33 UTC, Sean-Nishi commented on game/tiles/entities/items/crystal.py
> +        image_rect = pygame.Rect(
No type hints

2023-12-22 18:34 UTC, Sean-Nishi commented on game/tiles/entities/items/item.py
> +    status: str
Still not changed? Maybe another push required

2023-12-22 18:34 UTC, Sean-Nishi commented on game/tiles/entities/items/item.py
> +        self._animation_speed = 0.05
No type hints

2023-12-22 18:34 UTC, Sean-Nishi commented on game/tiles/entities/items/item.py
> +        crystal_spr_path = settings.ITEM_IMAGES + "crystal.png"
Maybe no shorthand for "spr"?

2023-12-22 18:35 UTC, Sean-Nishi commented on game/tiles/entities/items/item.py
> +            "imageCount": 3,
No CamelCase

2023-12-22 18:35 UTC, Sean-Nishi commented on game/tiles/entities/items/item.py
> +        animation_dicts = [idle_animation]
No type hint

2023-12-22 18:37 UTC, Sean-Nishi commented on game/tiles/entities/entity.py
> +        self.image = self._sprite_sheet.image_at(image_rect)
Private var should have _

2023-12-22 18:38 UTC, Sean-Nishi commented on game/tiles/entities/items/item.py
> +        self.image = self.animate()
This is updating Entity's (parent class) self.image, which should be private. Will fix in property decorator/safe access patch

2023-12-22 18:38 UTC, Sean-Nishi requested changes
Lots of CamelCase

2023-12-22 18:42 UTC, owalk commented on game/tiles/entities/items/item.py
> +        self.image = self.animate()
yeah image as a property and also rect as a property will fix this. that'll be in so many files

2023-12-22 18:45 UTC, owalk commented on game/tiles/entities/items/item.py
> +    status: str
ah, I thought I got this :(

2023-12-22 18:59 UTC, owalk commented on game/tiles/entities/items/item.py
> +        crystal_spr_path = settings.ITEM_IMAGES + "crystal.png"
this code also doesn't belong here, got forgotten in a refactor.

2023-12-22 19:07 UTC, owalk commented on game/tiles/entities/entity.py
> +        self.image = self._sprite_sheet.image_at(image_rect)
pygame needs to have an image attribute, and that's a separate issue since it will touch many files.

image and rect both need these

2023-12-22 20:01 UTC, Sean-Nishi commented on game/dict_structures/animation_dict.py
> +            'imageRect': pygame.Rect
Update docstring so no CamelCase

2023-12-22 20:04 UTC, Sean-Nishi commented on game/tiles/entities/characters/player.py
> +        player_self_imageRect = pygame.Rect(
type hints and CamelCase

2023-12-22 20:05 UTC, Sean-Nishi commented on game/tiles/entities/entity.py
> +    def animate(self) -> pygame.Surface:
Return value docstring

2023-12-22 20:05 UTC, Sean-Nishi commented on game/tiles/entities/entity.py
> +    def import_assets(self, animation_dict: list[AnimationDict]):
Requires "-> None"

2023-12-22 20:06 UTC, Sean-Nishi commented on game/tiles/entities/items/crystal.py
> +        image_rect: pygame.rect = pygame.Rect(
pygame.Rect type

2023-12-22 20:06 UTC, Sean-Nishi commented on game/tiles/entities/items/item.py
> +        groups: pygame.sprite.Group
Groups is now singular

2023-12-22 20:07 UTC, Sean-Nishi commented on game/tiles/entities/items/item.py
> +            The groups this sprite is a part of
Groups is now singular

2023-12-22 20:07 UTC, Sean-Nishi commented on game/tiles/entities/items/item.py
> +        self._animation_speed: int = 0.05
Float type?

2023-12-22 20:07 UTC, Sean-Nishi requested changes
Few more small things

2023-12-22 20:31 UTC, Sean-Nishi approved these changes

2023-12-22 20:32 UTC, merged