Make initial HUD and fix pause issues
Sean-Nishi/Reluctant-Hero pull request #312
Opened 2023-12-26 20:45 UTC by owalk

pause now works with the escape key as well as the HUD button for it.

2023-12-26 23:02 UTC, Sean-Nishi commented on game/HUD.py
> +    """ScoreController class.
Incorrect type

2023-12-26 23:03 UTC, Sean-Nishi commented on game/HUD.py
> +    PAUSE_BUTTON_HEITH = 30
Spelling

2023-12-26 23:04 UTC, Sean-Nishi commented on game/HUD.py
> +        If singleton already exists returns the previous singleton object
```suggestion
If instance already exists returns the previous singleton object
```

2023-12-26 23:06 UTC, Sean-Nishi commented on game/HUD.py
> +    ):
```suggestion
def __init__(self):
```

2023-12-26 23:08 UTC, Sean-Nishi commented on game/HUD.py
> +        self.__current_score_spr = Text(
```suggestion
        self._current_score_spr = Text(
```

2023-12-26 23:10 UTC, Sean-Nishi commented on game/HUD.py
> +        self.__boredom_meter_spr = Text(
Double underscores used on private vars. Rename symbol

2023-12-26 23:10 UTC, Sean-Nishi commented on game/HUD.py
> +        self.__current_score_value_spr = Text(
Double underscores used on private vars. Rename symbol

2023-12-26 23:10 UTC, Sean-Nishi commented on game/HUD.py
> +        self.__boredom_meter_value_spr = Text(
Double underscores used on private vars. Rename symbol

2023-12-26 23:12 UTC, Sean-Nishi commented on game/HUD.py
> +        self.pause_level = not self.pause_level
Private var needs preceding underscore. Also vars are only referenced in this method

2023-12-26 23:13 UTC, Sean-Nishi commented on game/HUD.py
> +        sprite.image = pygame.Surface((height, width))
New vars need type hints, even if it is obvious like in this spot ☹️

2023-12-26 23:13 UTC, Sean-Nishi commented on game/HUD.py
> +    add_box(self, rect, height, width)
Needs return value

2023-12-26 23:14 UTC, Sean-Nishi commented on game/HUD.py
> +        self.__boredom_meter_value_spr.text_str = self._score.boredom_meter
Only one preceding underscore needed. Rename symbol

2023-12-26 23:15 UTC, Sean-Nishi commented on game/HUD.py
> +                level_hint_rect = pygame.Rect(
Typehint

2023-12-26 23:18 UTC, Sean-Nishi commented on game/HUD.py
> +    current_score(self)
Method removed. Docstring update required

2023-12-26 23:19 UTC, Sean-Nishi commented on game/button.py
> +    _onePress: boolean
Name of var has type. Needs snake_case

2023-12-26 23:20 UTC, Sean-Nishi commented on game/button.py
> +        If the button is already pressed
Name of var has type. Needs snake_case

2023-12-26 23:21 UTC, Sean-Nishi commented on game/button.py
> +        Button text to display
Name of var has type. Needs snake_case

2023-12-26 23:21 UTC, Sean-Nishi commented on game/button.py
> +    _text_image: pygame.surface
Incorrect type

2023-12-26 23:22 UTC, Sean-Nishi commented on game/button.py
> +        Set the text string value
Method names are short enough to type out "string" fully. Want to avoid shorthand

2023-12-26 23:22 UTC, Sean-Nishi commented on game/button.py
> +    ):
Parameters require typehints

2023-12-26 23:23 UTC, Sean-Nishi commented on game/button.py
> +        self._onclickFunction: callable = onclickFunction
Rename symbol to be snake_case

2023-12-26 23:24 UTC, Sean-Nishi commented on game/button.py
> +        self._buttonText: str = buttonText
Symbols should be in snake_case. Rename symbol

2023-12-26 23:24 UTC, Sean-Nishi commented on game/button.py
> +        mousePos: tuple = pygame.mouse.get_pos()
Symbol should be snake_case

2023-12-26 23:25 UTC, Sean-Nishi commented on game/button.py
> +    Methods
Only method is update(self)

2023-12-26 23:29 UTC, Sean-Nishi commented on game/game.py
> +        ScoreController()
Quick question: Are we not assigning a handle to these because they are singleton?

2023-12-26 23:33 UTC, Sean-Nishi commented on game/text.py
> +        self.rect = pygame.Rect(x_pos, y_pos, 50, 50)
Typehints required

2023-12-26 23:33 UTC, Sean-Nishi commented on game/text.py
> +        The current score for the game
Attributes do not match what is in init

2023-12-26 23:34 UTC, Sean-Nishi commented on game/text.py
> +    text_str(self)
Return type required

2023-12-26 23:36 UTC, Sean-Nishi requested changes
Just the comments I added

2023-12-27 14:29 UTC, owalk commented on game/game.py
> +        ScoreController()
Yeah, The purpose of these lines of code is to run the initializer before any of the other classes need to use these singletons. There is no need to access them in the main method, so adding a way to access them here would add clutter to the main method.

2023-12-27 14:40 UTC, owalk commented on game/text.py
> +    text_str(self)
I hadn't been adding the return type to the class doc strings since it's in the method doc strings.
I'll add this in

2023-12-27 14:41 UTC, owalk commented on game/text.py
> +    text_str(self)
but only when it is not None

2023-12-27 15:02 UTC, owalk commented on game/HUD.py
> +        self.__current_score_spr = Text(
aren't we mangling private vars and using a single underscore on protected vars?

2023-12-27 15:10 UTC, owalk commented on game/HUD.py
> +        self.__current_score_spr = Text(
I think a bunch of our single underscores should be double and we might want a new issue for this. it's marginal benefits and doesn't matter too much in the grand scheme of things

2023-12-27 15:13 UTC, owalk commented on game/HUD.py
> +        self.pause_level = not self.pause_level
this is the attribute defined on lines 213 and 218. It's used in main and level.py

2023-12-27 15:19 UTC, owalk commented on game/HUD.py
> +        sprite.image = pygame.Surface((height, width))
wait the only new var here is sprite :O I think we just need the one type hint on line 137 for these

2023-12-27 15:20 UTC, owalk commented on game/HUD.py
> +        self.__boredom_meter_value_spr.text_str = self._score.boredom_meter
I'm gonna wait for you to respond to my comments on should we mangle private vars before changing these

2023-12-27 15:23 UTC, owalk commented on game/HUD.py
> +        If singleton already exists returns the previous singleton object
spacing change suggestion not added, wording suggestion added

2023-12-27 16:10 UTC, Sean-Nishi commented on game/text.py
> +    image: pygane.Surface
Spelling

2023-12-27 17:35 UTC, owalk commented
@Sean-Nishi before I fix the one new comment it would be nice to have the other comments addressed and closed out

2023-12-27 17:42 UTC, owalk commented on game/text.py
> +    image: pygane.Surface
okay i went ahead and just fixed this, but the previous comments have not been resolved yet

2023-12-27 18:11 UTC, Sean-Nishi commented on game/button.py
> +    _button_text: str
```suggestion
    _button_text_string: str
```

2023-12-27 18:12 UTC, Sean-Nishi approved these changes

2023-12-27 18:13 UTC, merged