Finished 24 and fixed merge conflicts with main
Sean-Nishi/Reluctant-Hero pull request #315
Opened 2023-12-27 20:26 UTC by Sean-Nishi

2023-12-27 20:31 UTC, owalk commented
In git under normal circumstances, you should never need to specify that you are fixing a merge conflict. That should be done locally so that the git history on main is seamless. The only situation a PR would address a merge conflict is if the main branch's git history was broken and that somehow got through a review, which should honestly never happen unless we are incredibly sloppy with reviews or commit history.

2023-12-27 20:33 UTC, owalk commented
The commit scope for the single commit should probably be "Add background music for menu". I am going to review under the assumption that I'm correct in what the commit scope is, but please fix the commit title to the correct scope

2023-12-27 20:35 UTC, owalk commented on .vscode/settings.json
> +    "python.analysis.extraPaths": [
This file change is outside of the scope of this commit and should not be included in this commit. I suggest reverting the file.

If the change is intentional please move it to another commit with the correct scope to describe the change

2023-12-27 20:47 UTC, Sean-Nishi commented on .vscode/settings.json
> +    "python.analysis.extraPaths": [
I am so sick of github or vscode changing files that I don't touch. Reverted to origin/main's

2023-12-27 20:52 UTC, owalk requested changes

2023-12-27 20:52 UTC, owalk commented on game/levels/level.py
> +    def pause_menu(self) -> None:
This method is not needed and was removed in my last PR. 
To pause, we just check the value stored in HUD to see if sprites should update

2023-12-27 20:52 UTC, owalk commented on game/settings.py
> -MAIN_MENU_BACKGROUND_PATH = "game_assets/graphics/main_menu/ground.png"
moving this into the dict is such a low-hanging fruit to put in it's own narrowly scoped commit that I would personally have chosen to do it in another commit. This is fine as is.

2023-12-27 20:52 UTC, owalk commented on game/menus/main_menu/main_menu.py
> -        self._display_surface.blit(self._menu_image, (0, 0))
this change has nothing to do with music and is unclear why it is in here. please move to another commit

2023-12-27 20:52 UTC, owalk commented on game/menus/main_menu/main_menu.py
> -        self._menu_image: pygame.Surface = pygame.image.load(MAIN_MENU_BACKGROUND_PATH)
nothing to do with menu music

2023-12-27 20:56 UTC, owalk commented on .vscode/settings.json
> +    "python.analysis.extraPaths": [
you can use git update-index to manage this. https://stackoverflow.com/questions/4348590/how-can-i-make-git-ignore-future-revisions-to-a-file

2023-12-27 21:00 UTC, owalk commented on game/managers/asset_manager.py
> +                continue
There is potential for an infinite loop here. It needs either error handling to escape infinite loops or to be done less destructively.

I don't like pausing the entire game thread in a single-threaded application while the music loads. Is this loop needed?

2023-12-27 21:02 UTC, owalk commented on game/managers/asset_manager.py
> +                continue
how long does it take to load music? I'm suspicious about this. It would also only make sense to wait if there is some sort of noticeable load time

2023-12-27 21:03 UTC, owalk commented on game/menus/main_menu/main_menu.py
> +from settings import WINDOW_WIDTH, WINDOW_HEIGHT
outside of music commit scope. belongs on a second commit

2023-12-27 21:05 UTC, owalk commented on game/levels/level.py
> +    def create_map(self, level_dict: dict) -> None:
the commit history would be much cleaner with a commit scoped to just the name change for this attr. you could include it in this commit scope, but generally never have 2 different issues addressed in 1 commit unless they are very related to each other

2023-12-27 21:06 UTC, owalk commented on game/levels/level.py
> +        layout: array of values representing an individual entity from the map
another solid change out of scope for a commit to address music

2023-12-27 21:07 UTC, owalk commented on game/levels/level.py
> +    create_entities_from_layout(self, layout: list[int])
List to list is also out of scope for music changes

2023-12-29 19:52 UTC, owalk commented on game/game_data.py
> +        "music": "game_assets/music/main_menu/science-documentary-169621.mp3",
made a new issue to rename files [here](https://github.com/Sean-Nishi/Reluctant-Hero/issues/320)

2023-12-29 19:57 UTC, owalk requested changes

2023-12-29 19:57 UTC, owalk commented on game/menus/main_menu/main_menu.py
> +        main_menu_dict:dict
looks like there aren't any parameters here

2023-12-29 19:57 UTC, owalk commented on game/managers/asset_manager.py
> +    add_music(self, menu_flag: str, key: str)
should this be load music instead of add music?

2023-12-29 19:58 UTC, Sean-Nishi commented on game/game_data.py
> +        "music": "game_assets/music/main_menu/science-documentary-169621.mp3",
Adding as a commit to a new pr

2023-12-29 20:20 UTC, owalk approved these changes

2023-12-29 20:22 UTC, merged